CREATE TABLE IF NOT EXISTS category(
    id SERIAL NOT NULL PRIMARY KEY,
    category_name VARCHAR(155),
    status BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)