CREATE TABLE IF NOT EXISTS sub_category (
    id SERIAL NOT NULL PRIMARY KEY,
    subcategory_name VARCHAR(155),
    category_id INT REFERENCES category(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)