CREATE TABLE IF NOT EXISTS views(
    id SERIAL NOT NULL PRIMARY KEY,
    book_id INT REFERENCES books(id) ON DELETE CASCADE,
    user_agent VARCHAR,
    count INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);